web/router.ex
defmodule L5rScheduler.Router do
  use L5rScheduler.Web, :router

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.LoadResource
  end

  pipeline :browser_auth do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.EnsureAuthenticated, handler: L5rScheduler.Token
    plug Guardian.Plug.LoadResource
  end

  scope "/", L5rScheduler do
    pipe_through :browser # Use the default browser stack

    get "/",       GameScheduleController, :index
    get "/logout", SessionController,      :delete

    resources "/sessions", SessionController, only: [:new, :create]
    resources "/users",    UserController,    only: [:new, :create]
  end

  scope "/", L5rScheduler do
    pipe_through [:browser, :browser_auth]

    resources "/characters",     CharacterController
    resources "/game_schedules", GameScheduleController
    resources "/users",          UserController, only: [:edit, :update]
  end

  # Other scopes may use custom stacks.
  # scope "/api", L5rScheduler do
  #   pipe_through :api
  # end
end

web/views/layout_view.ex
defmodule L5rScheduler.LayoutView do
  use L5rScheduler.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello L5rScheduler!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
<%= if logged_in?(@conn) do %>
            <li><%= link "Schedule", to: game_schedule_path(@conn, :index) %></li>
            <li><%= link "Characters", to: character_path(@conn, :index) %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>
                <%= current_user(@conn).username %>
                <span class="caret"></span></a>
              </a>
              <ul class="dropdown-menu pull-right">
                <li><%= link "Edit Profile", to: user_path(@conn, :edit, current_user(@conn)) %></li>
                <li><%= link "New Character", to: character_path(@conn, :new) %></li>
<%= if current_user(@conn).admin do %>
                <li><%= link "New Game Schedule", to: game_schedule_path(@conn, :new) %></li>
<% end %>
                <li><%= link "Sign Out", to: "/logout" %></li>
              </ul>
            </li>
<% else %>
            <li><%= link "Sign In", to: session_path(@conn, :new) %></li>
            <li><%= link "Sign Up", to: user_path(@conn, :new) %></li>
<% end %>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>